// Generated by CoffeeScript 1.9.1
var fs, inquirer, interactiveConfig, yaml;

inquirer = require('inquirer');

fs = require('fs');

yaml = require('js-yaml');

interactiveConfig = {};

interactiveConfig.prompt = function(config, callback) {
  var questions, ref, ref1;
  if (config == null) {
    config = {};
  }
  questions = [];
  questions.push({
    type: "input",
    name: "blueprint",
    message: "Location of the API bleuprint",
    "default": config['blueprint'] || "apiary.apib"
  });
  questions.push({
    type: "input",
    name: "server",
    message: "Command to start API backend server",
    "default": config['server'] || "rails server"
  });
  questions.push({
    type: "input",
    name: "endpoint",
    message: "URL of tested API endpoint",
    "default": config['endpoint'] || "http://localhost:3000"
  });
  questions.push({
    type: "confirm",
    name: "apiary",
    message: "Do you want to use Apiary test inspector?",
    "default": true,
    when: function(answers) {
      return config['reporter'] !== 'apiary';
    }
  });
  questions.push({
    type: "input",
    name: "apiaryApiKey",
    message: "Please enter Apiary API key or leave empty for anonymous reporter",
    "default": (ref = config['custom']) != null ? ref['apiaryApiKey'] : void 0,
    when: function(answers) {
      var ref1;
      return answers['apiary'] === true && (((ref1 = config['cusotom']) != null ? ref1['apiaryApiKey'] : void 0) == null);
    }
  });
  questions.push({
    type: "input",
    name: "apiaryApiName",
    message: "Please enter Apiary API name",
    "default": (ref1 = config['custom']) != null ? ref1['apiaryApiName'] : void 0,
    when: function(answers) {
      var ref2;
      return answers['apiary'] === true && (((ref2 = config['custom']) != null ? ref2['apiaryApiName'] : void 0) == null);
    }
  });
  questions.push({
    type: "confirm",
    name: "travisAdd",
    message: "Found Travis CI configurtation, do you want to add Dredd to the build?",
    "default": true,
    when: function() {
      return fs.existsSync('.travis.yml');
    }
  });
  questions.push({
    type: "confirm",
    name: "circleAdd",
    message: "Found CircleCI configurtation, do you want to add Dredd to the build?",
    "default": true,
    when: function() {
      return fs.existsSync('circle.yml');
    }
  });
  questions.push({
    type: "rawlist",
    name: "ciCreate",
    message: "Dredd is best served with Continous Intregration. Create CI config for Dredd?",
    choices: ['CircleCI', 'Travis CI', 'Do not create CI configuration now.'],
    when: function(answers) {
      return !fs.existsSync('circle.yml') && !fs.existsSync('.travis.yml');
    }
  });
  return inquirer.prompt(questions, function(answers) {
    return callback(answers);
  });
};

interactiveConfig.processAnswers = function(config, answers, callback) {
  if (!config['_']) {
    config['_'] = [];
  }
  config['_'][0] = answers['blueprint'];
  config['_'][1] = answers['endpoint'];
  config['server'] = answers['server'];
  if (answers['apiary'] === true) {
    config['reporter'] = "apiary";
  }
  if (answers['apiaryApiKey'] != null) {
    config['custom']['apiaryApiKey'] = answers['apiaryApiKey'];
  }
  if (answers['apiaryApiName'] != null) {
    config['custom']['apiaryApiName'] = answers['apiaryApiName'];
  }
  if (answers['ciCreate'] === 'CircleCI' || answers['circleAdd']) {
    interactiveConfig.updateCircle();
  }
  if (answers['ciCreate'] === 'Travis CI' || answers['travisAdd']) {
    interactiveConfig.updateTravis();
  }
  return callback(config);
};

interactiveConfig.run = function(config, callback) {
  return interactiveConfig.prompt(config, function(answers) {
    return interactiveConfig.processAnswers(config, answers, function(newConfig) {
      return callback(newConfig);
    });
  });
};

interactiveConfig.updateCircle = function() {
  var config, file, yamlData;
  file = "circle.yml";
  if (fs.existsSync(file)) {
    config = yaml.safeLoad(fs.readFileSync(file));
  } else {
    config = {};
  }
  if (config['dependencies'] == null) {
    config['dependencies'] = {};
  }
  if (!config['dependencies']['pre']) {
    config['dependencies']['pre'] = [];
  }
  if (config['dependencies']['pre'].indexOf("npm install -g dredd") === -1) {
    config['dependencies']['pre'].push("npm install -g dredd");
  }
  if (config['test'] == null) {
    config['test'] = {};
  }
  if (!config['test']['pre']) {
    config['test']['pre'] = [];
  }
  if (config['test']['pre'].indexOf("dredd") === -1) {
    config['test']['pre'].push("dredd");
  }
  yamlData = yaml.safeDump(config);
  return fs.writeFileSync(file, yamlData);
};

interactiveConfig.updateTravis = function() {
  var config, file, yamlData;
  file = ".travis.yml";
  if (fs.existsSync(file)) {
    config = yaml.safeLoad(fs.readFileSync(file));
  } else {
    config = {};
  }
  if (config['before_install'] == null) {
    config['before_install'] = [];
  }
  if (config['before_install'].indexOf("npm install -g dredd") === -1) {
    config['before_install'].push("npm install -g dredd");
  }
  if (config['before_script'] == null) {
    config['before_script'] = [];
  }
  if (config['before_script'].indexOf("dredd") === -1) {
    config['before_script'].push("dredd");
  }
  yamlData = yaml.safeDump(config);
  return fs.writeFileSync(file, yamlData);
};

module.exports = interactiveConfig;
